name: 'Require Additional Reviewer'
description: 'Require additional reviewers of automatically created Pull Requests.'

inputs:
  artifact-name:
    description: 'The name of the artifact containing the release PR author name.'
    default: 'release-authors'
    required: true
  artifact-workflow-name:
    description: 'The name of the workflow that writes the release author artifact.'
    default: 'Create Release Pull Request'
    required: true
  artifacts-path:
    description: 'The path to the directory where this action will look for its required artifacts.'
    default: 'gh-action__release-authors'
    required: true
  release-branch-prefix:
    description: 'The prefix of release PR branch names for this repository.'
    default: 'release/'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check Branch Prefix
      id: check-branch-prefix
      shell: bash
      run: |
        PREFIX_MATCH=$(
          echo "${{ github.head_ref }}" | grep -o "^${{ inputs.release-branch-prefix }}"
        )

        if [[ -n $PREFIX_MATCH ]]; then
          IS_RELEASE="true"
        else
          IS_RELEASE="false"
        fi

        echo "::set-output name=is-release::$IS_RELEASE"

    - name: Download Release Author Artifact
      shell: bash
      run: |
        if [[ "${{ steps.check-branch-prefix.outputs.is-release }}" == "true" ]]; then
          ${{ github.action_path }}/scripts/download-artifact.sh \
            "${{ github.repository }}" \
            "${{ github.base_ref }}" \
            "${{ inputs.artifacts-path }}" \
            "${{ inputs.artifact-name }}" \
            "${{ inputs.artifact-workflow-name }}"
        fi

    - name: Check for Additional Reviewers
      id: check-additional-reviewers
      shell: bash
      run: |
        if [[ "${{ steps.check-branch-prefix.outputs.is-release }}" == "true" ]]; then
          ${{ github.action_path }}/scripts/check-for-additional-reviewers.sh \
            "${{ github.event.pull_request.number }}" \
            "${{ inputs.artifacts-path }}"
        fi

    - name: Set Commit Status
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/set-commit-status.sh \
          "${{ github.repository }}" \
          "${{ steps.check-branch-prefix.outputs.is-release }}" \
          "${{ steps.check-additional-reviewers.outputs.num-other-approving-reviewers }}"
