name: Require Additional Reviewer for Releases

on:
  pull_request:
  pull_request_review:

jobs:
  require-additional-reviewer:
    permissions:
      actions: read
      contents: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
